# Generated by Django 5.0.4 on 2024-04-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='content',
            new_name='prompt',
        ),
        migrations.AddField(
            model_name='chat',
            name='response',
            field=models.TextField(default='old'),
            preserve_default=False,
        ),
    ]
