# Generated by Django 5.0.4 on 2024-04-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_content_chat_prompt_chat_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
