version: '3.8'
services:
  django:
    build: ./backend
    volumes:
      - ./backend:/app
    expose:
      - 8000

  react:
    build: ./frontend
    volumes:
      - react-build:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - django

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - react-build:/usr/share/nginx/html
    depends_on:
      - react

volumes:
  react-build:
